---
- name: Setting up wordpress
  hosts: all
  tasks:
    - name: Update repositories 
      become: true
      apt:
        #upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #A day
      
    - name: Install php dependencies
      become: true
      apt:
        name:
          - php-cli
          - php-fpm
          - php-mysql
          - php-json
          - php-opcache
          - php-mbstring
          - php-xml
          - php-gd
          - php-curl
        state: present
     
    - name: Install nginx
      become: true
      apt:
        name: nginx 
        state: present
     
    
    - name: Install MySQL Server
      become: true
      apt:
        name: 
          - mysql-server
          - python3-pymysql  
        state: present
    
    # Set MySQL root Password on Ansible/Ubuntu - https://linuxhint.com/set_mysql_root_password_ansible/ 
    - name: Relax the MySQL root user
      shell: sudo mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password"
       WHERE user="root" AND host="localhost"'

    - name: Flush Privileges
      shell: sudo mysql -u root -e 'FLUSH PRIVILEGES'

    - name: Create SQL user 
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: wp_user
        password: wp_password
        priv: "*.*:ALL"
        state: present
     
    - name: Create DB for wordpress
      mysql_db:
        login_host: 'localhost'
        login_user: 'wp_user'
        login_password: 'wp_password'
        name: wp_db
        state: present
    
    - name: Check if wp-cli exists
      stat: path="/bin/wp"
      register: wpcli_exist
      tags:
        - always

    - name: Updating wp-cli
      become: true
      shell: "/bin/wp cli update --yes"
      when: wpcli_exist.stat.exists
      tags:
        - wp
        - update
    
    - name: Download wp-cli
      become: true
      get_url:
        url="https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
        dest="/bin/wp"
        force_basic_auth=yes
        mode=0755
      when: not wpcli_exist.stat.exists
      tags:
        - wp
        - install  
    
    - name: Install Wordpress
      shell: "sudo wp core download --path=/var/www/html/wordpress --allow-root"
      register: wp_installed

    - name: Configure Wordpress DB Connection
      shell: "sudo wp config create --dbname=wp_db --dbuser=wp_user --dbpass=wp_password --path=/var/www/html/wordpress --allow-root"

    - name: Configure Wordpress Admin User
      shell: 'sudo wp core install --url="192.168.50.2" --title="Blogging Platform" --admin_user=admin --admin_email=danpal@example.com --admin_password="!2three456." --path=/var/www/html/wordpress --allow-root'

